// src/components/ThemeToggle.tsx
import { Moon, Sun } from 'lucide-react';
import { useEffect, useState } from 'react';
import SmoothButton from './ui/smoothui/smooth-button';

export default function ThemeToggle() {
  const [dark, setDark] = useState(true);

  useEffect(() => {
    const isDark = document.documentElement.classList.contains('dark');
    setDark(isDark);
  }, []);

  const toggle = () => {
    const nextDark = !dark;
    document.documentElement.classList.toggle('dark', nextDark);
    localStorage.setItem('resume-theme', nextDark ? 'dark' : 'light');
    setDark(nextDark);
  };

  return (
    <SmoothButton
      aria-label={dark ? 'Switch to light mode' : 'Switch to dark mode'}
      className="rounded-full"
      onClick={toggle}
      size="icon-sm"
      variant="ghost"
    >
      {dark ? <Sun aria-hidden="true" /> : <Moon aria-hidden="true" />}
    </SmoothButton>
  );
}

// src/components/ThemeToggle.svelte
<script lang="ts">
  let theme = $state<'dark' | 'light'>('dark');

  function toggle() {
    theme = theme === 'dark' ? 'light' : 'dark';
    document.documentElement.dataset.theme = theme;
    localStorage.setItem('resume-theme', theme);
  }
</script>

<button class="theme-toggle" type="button" aria-label="切換深色與淺色模式" onclick={toggle}>
  {theme === 'dark' ? '切換淺色' : '切換深色'}
</button>
